#!/usr/bin/env python3
"""Validate the workspace generated by the CMake LeetGPU integration."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

DIFFICULTIES = ("easy", "medium", "hard")


def rel_challenge(starter: Path, upstream: Path) -> Path:
    # challenges/easy/1_vector_add/starter/starter.cu -> easy/1_vector_add
    rel = starter.relative_to(upstream / "challenges")
    return Path(rel.parts[0]) / rel.parts[1]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--upstream", type=Path, required=True)
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--build", type=Path, required=True)
    args = parser.parse_args()

    upstream = args.upstream.resolve()
    source = args.source.resolve()
    build = args.build.resolve()

    starters = sorted(
        starter
        for difficulty in DIFFICULTIES
        for starter in (upstream / "challenges" / difficulty).glob("*/starter/starter.cu")
    )
    if not starters:
        raise SystemExit("no upstream CUDA starters found")

    expected = {rel_challenge(starter, upstream) for starter in starters}
    generated = {
        solution.parent.relative_to(source / "solutions")
        for solution in (source / "solutions").glob("*/*/solution.cu")
    }

    missing = sorted(expected - generated)
    extra = sorted(generated - expected)
    if missing or extra:
        if missing:
            print("missing generated solutions:")
            for path in missing:
                print(f"  {path}")
        if extra:
            print("unexpected generated solutions:")
            for path in extra:
                print(f"  {path}")
        return 1

    compile_db = build / "compile_commands.json"
    entries = json.loads(compile_db.read_text())
    compiled_solutions = {
        Path(entry["file"]).resolve().parent.relative_to(source / "solutions")
        for entry in entries
        if Path(entry["file"]).name == "solution.cu"
    }
    missing_from_db = sorted(expected - compiled_solutions)
    if missing_from_db:
        print("solutions missing from compile_commands.json:")
        for path in missing_from_db:
            print(f"  {path}")
        return 1

    counts = {
        difficulty: sum(path.parts[0] == difficulty for path in expected)
        for difficulty in DIFFICULTIES
    }
    print(
        "validated "
        f"{len(expected)} challenges "
        f"(easy={counts['easy']}, medium={counts['medium']}, hard={counts['hard']})"
    )
    print(f"compile_commands.json contains {len(compiled_solutions)} CUDA solution entries")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
